# Generated by Django 5.0 on 2024-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Chapa', models.CharField(max_length=255)),
                ('Horario_do_almoço', models.TimeField()),
                ('Departamento', models.CharField(max_length=255)),
                ('PN', models.CharField(blank=True, max_length=255, null=True)),
                ('Gestor', models.CharField(blank=True, max_length=255, null=True)),
                ('CPF', models.CharField(blank=True, max_length=255, null=True)),
                ('rotaDaFoto', models.CharField(max_length=255)),
                ('Usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('Senha', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('GestorCheck', models.BooleanField(default=False)),
                ('EngenhariaComumEngenharia', models.BooleanField(default=False)),
                ('Engenhariaengenharia', models.BooleanField(default=False)),
                ('OuvidoriaAdministraoRH', models.BooleanField(default=False)),
                ('TITOOLSTI', models.BooleanField(default=False)),
                ('ReembolsoComumreembolso', models.BooleanField(default=False)),
                ('ReembolsoGestorreembolso', models.BooleanField(default=False)),
                ('ReembolsoContabilidadereembolso', models.BooleanField(default=False)),
                ('ReembolsoAdministraoreembolso', models.BooleanField(default=False)),
                ('id_departamento', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
