#!/bin/bash

# Diretório de logs
LOG_DIR="/var/www/html/eng/engenharia/logs"
mkdir -p "$LOG_DIR"

# Iniciar o servidor frontend e direcionar logs
cd /var/www/html/engenharia/engenharia/frontc
nohup sh -c 'HOST=alpinacloud.com.br PORT=5175 npm run frontend' > "$LOG_DIR/frontend.log" 2>&1 &

echo "Servidor frontend iniciado, logs em $LOG_DIR/frontend.log"

# Aguardar alguns segundos para o servidor frontend iniciar completamente
sleep 5

# Iniciar o servidor Celery e direcionar logs
cd /var/www/html/engenharia/engenharia/back/backengenharia
source venv/bin/activate

nohup celery -A backengenharia worker -l info > "$LOG_DIR/celery.log" 2>&1 &
echo "Servidor Celery iniciado, logs em $LOG_DIR/celery.log"




# Aguardar alguns segundos para o Celery iniciar completamente
sleep 5

# Iniciar o servidor backend com Gunicorn e direcionar logs
nohup python3 -m gunicorn backengenharia.wsgi:application --bind alpinacloud.com.br:8007 --workers 3 > "$LOG_DIR/backend.log" 2>&1 &

echo "Servidor backend (Gunicorn) iniciado, logs em $LOG_DIR/backend.log"

echo "Todos os servidores foram iniciados com sucesso. Verifique os logs em $LOG_DIR"
