# Generated by Django 5.0 on 2024-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventiladores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_ventilador', models.CharField(max_length=100, null=True)),
                ('numero_de_pas', models.IntegerField(default=0, null=True)),
                ('PSI', models.FloatField(null=True)),
                ('FI', models.FloatField(null=True)),
                ('resposta', models.FloatField(null=True)),
                ('angulo_da_pa', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'calculoVentiladores_ventiladores',
            },
        ),
    ]
