# Generated by Django 5.0 on 2024-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculoVentiladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DC_DV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_de_pas', models.IntegerField(null=True)),
                ('relacao_dc_dv', models.FloatField(null=True)),
                ('resultado', models.FloatField(null=True)),
                ('PWL', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'DC_DV',
            },
        ),
        migrations.CreateModel(
            name='HD_DA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relcao_hd_da', models.FloatField(null=True)),
                ('C', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'HD_DA',
            },
        ),
        migrations.CreateModel(
            name='relacao_d_delta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D', models.IntegerField(null=True)),
                ('DELTA', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'relacao_d_delta',
            },
        ),
    ]
