# Generated by Django 5.0 on 2024-05-16 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelecaoDadosPrincipais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=64, null=True)),
                ('Serie', models.IntegerField(null=True)),
                ('Tamanho', models.FloatField(null=True)),
                ('VarCont', models.FloatField(null=True)),
                ('Estrutura', models.FloatField(null=True)),
                ('FreqRedeElet', models.FloatField(null=True)),
                ('CompDasPas', models.FloatField(null=True)),
                ('DiamVent', models.FloatField(null=True)),
                ('AreaSecTrans', models.FloatField(null=True)),
                ('ASP2Lados', models.CharField(max_length=64, null=True)),
                ('ASP3Lados', models.FloatField(null=True)),
                ('INSASP4Lados', models.FloatField(null=True)),
                ('NVent', models.BooleanField(default=True)),
                ('AltEntAgua', models.CharField(max_length=64, null=True)),
                ('NumPasVentClasse1', models.IntegerField(null=True)),
                ('RotVentC1', models.FloatField(null=True)),
                ('PotMotEletC1', models.FloatField(null=True)),
                ('RotMotEletC1', models.FloatField(null=True)),
                ('DiamVentPadraoC1', models.FloatField(null=True)),
                ('NPasVentC2', models.FloatField(null=True)),
                ('RotDoVentC2', models.FloatField(null=True)),
                ('PotMotEletC2', models.FloatField(null=True)),
                ('RotMotEletC2', models.CharField(max_length=64, null=True)),
                ('DiamVentPadraoC2', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'calculoSelecao_SelecaoDadosPrincipais',
            },
        ),
        migrations.CreateModel(
            name='SelecaoCamadasDeEnchimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TorresComA19Nmax', models.CharField(max_length=64, null=True)),
                ('TorresComA19Nmin', models.FloatField(null=True)),
                ('TorresComSGeW20Nmax', models.FloatField(null=True)),
                ('TorresComSGeW20Nmin', models.FloatField(null=True)),
                ('TorresComRTNmax', models.CharField(max_length=64, null=True)),
                ('TorresComRTNmin', models.FloatField(null=True)),
                ('TorresComSGCNmax', models.FloatField(null=True)),
                ('TorresComSGCNmin', models.FloatField(null=True)),
                ('idDadosPrincipais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculoSelecao.selecaodadosprincipais')),
            ],
            options={
                'db_table': 'Selecao_SelecaoCamadasDeEnchimento',
            },
        ),
        migrations.CreateModel(
            name='charsTorre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PressMaxEnt', models.FloatField(null=True)),
                ('TipCuboVentil', models.FloatField(null=True)),
                ('LargCell', models.FloatField(null=True)),
                ('CompCell', models.FloatField(null=True)),
                ('TipEstrtut', models.CharField(max_length=64, null=True)),
                ('RevestLat', models.CharField(max_length=64, null=True)),
                ('TipDistrib', models.CharField(max_length=64, null=True)),
                ('idDadosPrincipais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculoSelecao.selecaodadosprincipais')),
            ],
            options={
                'db_table': 'Selecao_charsTorre',
            },
        ),
        migrations.CreateModel(
            name='charsMoteVent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipVentilC1', models.CharField(max_length=64, null=True)),
                ('TipVentilC2', models.CharField(max_length=64, null=True)),
                ('DescMotEletC1', models.CharField(max_length=64, null=True)),
                ('DescMotEletC2', models.CharField(max_length=64, null=True)),
                ('tipPasVentilC1', models.CharField(max_length=64, null=True)),
                ('tipPasVentilC2', models.CharField(max_length=64, null=True)),
                ('tipoTransmC1', models.CharField(max_length=64, null=True)),
                ('tipoTransmC2', models.CharField(max_length=64, null=True)),
                ('rendTransmC1', models.FloatField(null=True)),
                ('rendTransmC2', models.FloatField(null=True)),
                ('idDadosPrincipais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculoSelecao.selecaodadosprincipais')),
            ],
            options={
                'db_table': 'Selecao_charsMotoreVentilador',
            },
        ),
        migrations.CreateModel(
            name='charsEnchimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doisSGW202ou3A192l', models.FloatField(null=True)),
                ('tresSGW204A192l', models.FloatField(null=True)),
                ('quatroou5SGW20ou5A192l', models.FloatField(null=True)),
                ('doisSGW202ou3A193l', models.FloatField(null=True)),
                ('tresSGW204A193l', models.FloatField(null=True)),
                ('quatroou5SGW20ou5A193l', models.FloatField(null=True)),
                ('doisSGW202ou3A194l', models.FloatField(null=True)),
                ('tresSGW204A194l', models.FloatField(null=True)),
                ('quatroou5SGW20ou5A194l', models.FloatField(null=True)),
                ('idDadosPrincipais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculoSelecao.selecaodadosprincipais')),
            ],
            options={
                'db_table': 'Selecao_charsEnchimento',
            },
        ),
        migrations.CreateModel(
            name='SelecaoPilaretes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AltPilAdcmPTorreCA19CAte4W20e4SGArPor2l', models.IntegerField(null=True)),
                ('AltPilAdcmPTorreCA19CAte4W20e4SGAPor3l', models.FloatField(null=True)),
                ('AltPilAdcmPTorreCA19CAte4W20e4SGAPor4l', models.FloatField(null=True)),
                ('AltPilAdcmCom5W20e5SGAPor2l', models.FloatField(null=True)),
                ('AltPilAdcmCom5W20e5SGArPor3l', models.FloatField(null=True)),
                ('AltPilAdcmCom5W20e5SGArPor4l', models.FloatField(null=True)),
                ('idDadosPrincipais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculoSelecao.selecaodadosprincipais')),
            ],
            options={
                'db_table': 'Selecao_SelecaoPilaretes',
            },
        ),
    ]
