# Generated by Django 5.0 on 2024-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculoSelecao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharsCamadasDeEnchimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('A1', models.CharField(blank=True, max_length=255, null=True)),
                ('A2', models.CharField(blank=True, max_length=255, null=True)),
                ('A3', models.CharField(blank=True, max_length=255, null=True)),
                ('A4', models.CharField(blank=True, max_length=255, null=True)),
                ('A5', models.CharField(blank=True, max_length=255, null=True)),
                ('A6', models.CharField(blank=True, max_length=255, null=True)),
                ('A7', models.CharField(blank=True, max_length=255, null=True)),
                ('A8', models.CharField(blank=True, max_length=255, null=True)),
                ('A9', models.CharField(blank=True, max_length=255, null=True)),
                ('A10', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua4ltpenc', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua3ltpenc', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua2ltpenc', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua4ltpencDepmodtorllentar', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua3ltpencDepmodtorllentar', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua2ltpencDepmodtorllentar', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua4ltpencDepmodtorllentarCamenc', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua3ltpencDepmodtorllentarCamenc', models.CharField(blank=True, max_length=255, null=True)),
                ('altentagua2ltpencDepmodtorllentarCamenc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'chars_camadas_de_enchimento',
            },
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='DescMotEletC1',
            new_name='DescricaoDoMotorEletricoC1',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='DescMotEletC2',
            new_name='DescricaoDoMotorEletricoC2',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='TipVentilC1',
            new_name='TipoDeVentiladorC1',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='TipVentilC2',
            new_name='TipoDeVentiladorC2',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='rendTransmC1',
            new_name='rendimentoDeTransmissaoC1',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='rendTransmC2',
            new_name='rendimentoDeTransmissaoC2',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='tipPasVentilC1',
            new_name='tipoDeTransmissaoC1',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='tipPasVentilC2',
            new_name='tipoDeTransmissaoC2',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='tipoTransmC1',
            new_name='tiposDePasDoVentiladorC1',
        ),
        migrations.RenameField(
            model_name='charsmotevent',
            old_name='tipoTransmC2',
            new_name='tiposDePasDoVentiladorC2',
        ),
        migrations.RemoveField(
            model_name='charsenchimento',
            name='idDadosPrincipais',
        ),
        migrations.RemoveField(
            model_name='charsmotevent',
            name='idDadosPrincipais',
        ),
        migrations.RemoveField(
            model_name='charstorre',
            name='idDadosPrincipais',
        ),
        migrations.AddField(
            model_name='charsenchimento',
            name='idDadosPrincipais_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='charsmotevent',
            name='idDadosPrincipais_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='charstorre',
            name='idDadosPrincipais_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='selecaodadosprincipais',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='selecaocamadasdeenchimento',
            name='idDadosPrincipais',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selecaodadosprincipais',
            name='Estrutura',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='selecaodadosprincipais',
            name='NVent',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='selecaodadosprincipais',
            name='Serie',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='selecaodadosprincipais',
            name='VarCont',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='selecaopilaretes',
            name='idDadosPrincipais',
            field=models.IntegerField(null=True),
        ),
    ]
