# Generated by Django 4.2.3 on 2023-11-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3600)),
                ('Cod', models.IntegerField()),
                ('comprimento_feixe', models.FloatField()),
                ('areas_transversais', models.FloatField()),
                ('largura', models.FloatField()),
                ('comprimento', models.FloatField()),
                ('altura', models.FloatField()),
                ('area_livre_ventilador', models.FloatField()),
                ('velocidade_periferica', models.FloatField()),
                ('MOD_FCA', models.CharField(max_length=3600)),
                ('N_feixes', models.FloatField()),
                ('N_tub_hor', models.FloatField()),
            ],
            options={
                'db_table': 'calculoFCA_fca',
            },
        ),
        migrations.CreateModel(
            name='Ventiladores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=3600)),
                ('diametro', models.FloatField()),
                ('potencia_do_motor', models.FloatField()),
                ('RPM_ventilador', models.FloatField()),
                ('id_FCA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculoFCA.fca')),
            ],
            options={
                'db_table': 'calculoFCA_ventiladores',
            },
        ),
        migrations.CreateModel(
            name='CharsFCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCA', models.IntegerField()),
                ('N_tub_ver', models.FloatField()),
                ('dis_entre_tub', models.FloatField()),
                ('diam_extern_tub', models.FloatField()),
                ('diam_intern_tub', models.FloatField()),
                ('exp_parede', models.FloatField()),
                ('condutibil_termic', models.FloatField()),
                ('id_FCA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculoFCA.fca')),
            ],
            options={
                'db_table': 'calculoFCA_charsfca',
            },
        ),
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=3600)),
                ('vazao', models.FloatField()),
                ('potencia', models.FloatField()),
                ('pressao', models.FloatField(default=8.0)),
                ('rotacao', models.FloatField(default=3500)),
                ('id_FCA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculoFCA.fca')),
            ],
            options={
                'db_table': 'calculoFCA_bomba',
            },
        ),
    ]
