# Generated by Django 4.2.3 on 2023-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculoFCA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fca',
            name='ativado',
            field=models.BooleanField(default=True),
        ),
    ]
