# Generated by Django 4.2.3 on 2023-12-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculoFCA', '0002_fca_ativado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_setor', models.CharField(max_length=255)),
                ('engenharia', models.CharField(max_length=255)),
                ('ouvidoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('chapa', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('horario_do_almoco', models.CharField(max_length=255)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('engenharia', models.CharField(max_length=255)),
                ('ouvidoria', models.CharField(max_length=255)),
                ('id_departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
