# Generated by Django 5.0 on 2024-05-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculoFCA', '0003_departamento_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
